version: '3.9'

services:
  web:
    build: .
    container_name: clipo_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - mongo
      - redis

  celery_worker:
    build: .
    container_name: clipo_worker
    command: celery -A app.celery_worker.celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - mongo
      - redis

  redis:
    image: redis:7-alpine
    container_name: clipo_redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6
    container_name: clipo_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
